Repository friendsofgo/killgrave, pull requests merged in 2020-10, with the labels that each got.

#62 Migrate CI/CD to Github Action
  .circleci/config.yml
  .github/workflows/main.yaml
  .github/workflows/release.yaml
Labels: hacktoberfest-accepted

#70 Refactor remove go core flag by cobra
  CHANGELOG.md
  README.md
  cmd/killgrave/main.go
  go.mod
  go.sum
  internal/app/cmd/cmd.go
  internal/app/cmd/http/http.go
  internal/app/killgrave.go
  internal/config.go
  internal/config_test.go
  internal/server/http/server.go
  internal/server/http/server_test.go
  internal/watcher.go
Labels: Hacktoberfest, hacktoberfest-accepted

#73 Windows tests fix from #71
  internal/server/http/route_matchers.go
Labels: hacktoberfest-accepted

#76 Improve readme
  CONTRIBUTING.md
  README.md
Labels: enhancement, hacktoberfest-accepted

#72 Implement YAML support for imposters
  internal/server/http/imposter.go
  internal/server/http/response_delay.go
  internal/server/http/server.go
  internal/server/http/test/testdata/imposters/test_request.imp.yaml
  internal/server/http/test/testdata/imposters/test_request.imp.yml
Labels: hacktoberfest-accepted
